// export const authConstants = {
//   LOGIN_REQUEST: 'LOGIN_REQUEST',
//   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
//   LOGIN_FAILURE: 'LOGIN_FAILURE',

//   LOGOUT_REQUEST: 'LOGOUT_REQUEST',
//   LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
//   LOGOUT_FAILURE: 'LOGOUT_FAILURE'
// }

// export const userSignUpConstants = {
//   USER_SIGNUP_REQUEST: 'SIGNUP_REQUEST',
//   USER_SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
//   USER_SIGNUP_FAILURE: 'SIGNUP_FAILURE'
// }
export const getCategoryConstants = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',

  ADD_CATEGORIES_REQUEST: 'ADD_CATEGORIES_REQUEST',
  ADD_CATEGORIES_SUCCESS: 'ADD_CATEGORIES_SUCCESS',
  ADD_CATEGORIES_FAILURE: 'ADD_CATEGORIES_FAILURE'
}
export const productConstants = {
  // ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  // ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  // ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',

  GET_PRODUCTS_BY_SLUG_REQUEST: 'GET_PRODUCTS_BY_SLUG_REQUEST',
  GET_PRODUCTS_BY_SLUG_SUCCESS: 'GET_PRODUCTS_BY_SLUG_SUCCESS',
  GET_PRODUCTS_BY_SLUG_FAILURE: 'GET_PRODUCTS_BY_SLUG_FAILURE'
}

// export const initialDataConstant = {
//   GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
//   GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
//   GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
// }
