export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userSignUpConstants = {
 USER_SIGNUP_REQUEST: 'SIGNUP_REQUEST',
 USER_SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
 USER_SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}